"""'fixed'

Revision ID: 6025c6f0a12e
Revises: f4485a86cc3d
Create Date: 2024-09-02 18:55:22.915470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6025c6f0a12e'
down_revision = 'f4485a86cc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipes_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['recipes_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipes_id')
    )
    # ### end Alembic commands ###
